# numpy.zeros

Sıfırla dolu bir numpy dizisi döndür.( ** Sıfır Matrisi** )

In [2]:
import numpy as np

In [3]:
np.zeros(5) #float olarak oluştu

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,), dtype=int) # int olarak

array([0, 0, 0, 0, 0])

In [4]:
np.zeros((3, 2)) # 3x2 boyutlarında

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# numpy.ones

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [7]:
 np.ones((2, 1))

array([[1.],
       [1.]])

# numpy.full

Bu metod ise hem **zeros** hem **ones** ı içinde barıyor. Çalışma mantığı boyut ve içlerine yerleştirilecek nesne.

In [8]:
np.full((2, 2), 'Udemy')

array([['Udemy', 'Udemy'],
       ['Udemy', 'Udemy']], dtype='<U5')

In [9]:
np.full((3, 2), 0) # np.zeros((3,2))

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
np.full((3, 2), 1) # np.ones((3,2))

array([[1, 1],
       [1, 1],
       [1, 1]])

# numpy.eye

Köşegende  1 , diğer kısımları  0 ile dolduran fonksiyon.

In [11]:
np.eye(2) #2x2 bir birim matris

array([[1., 0.],
       [0., 1.]])

In [12]:
np.eye(3) #3x3 bir birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3, k=1) # köşegeni 1 kaydırdık

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

![title](eyes.png)