# İki Diziyle Aritmetik İşlemler


**Dikkat ! **
İki dizi ile işlem yapmak için boyutlar önemli.

ilk önce 2 tane numpy dizisi oluşturalım.

In [1]:
import numpy as np

In [2]:
liste_1=[2,4,6,8] 

In [3]:
dizi_1=np.array(liste_1)# 4x1

In [4]:
dizi_1

array([2, 4, 6, 8])

Şimdi ikinci dizimizi oluşturalım

In [5]:
liste_2=[3,5,7,9]

In [6]:
dizi_2=np.array(liste_2) #4x1

In [7]:
dizi_2

array([3, 5, 7, 9])

### Toplama 

Dizi boyutları birbirine eşit olmalı.

In [8]:
dizi_1 + dizi_2

array([ 5,  9, 13, 17])

### Çıkarma

Dizi boyutları birbirine eşit olmalı.

In [9]:
dizi_1 - dizi_2

array([-1, -1, -1, -1])

### Çarpma

**! Uyarı**: NumPy dizileriyle matris çarpımı ,NumPy matris (matrix) nesneleriyle matris
çarpımından farklıdır!

In [10]:
dizi_1 * dizi_2 #burada boyutlar eşit olmalı,iç çarpım

array([ 6, 20, 42, 72])

In [12]:
a = np.matrix([[1,2],[0,2],[3,1]])

In [13]:
a.shape

(3, 2)

In [14]:
b = np.matrix([[4,3],[2,1]])

In [15]:
b.shape

(2, 2)

In [16]:
b *  a # !

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [17]:
np.dot(a, b) # burada matrislerin (...,m)x(m,...) özelliği kullanılıyor

matrix([[ 8,  5],
        [ 4,  2],
        [14, 10]])

**  2 Boyutta !**

np.dot() matris çarpımına eş değer.

In [18]:
a=np.array([[1,1],[1,1]])

In [19]:
a

array([[1, 1],
       [1, 1]])

In [20]:
b=np.array([[2,2],[2,2]])

In [21]:
b

array([[2, 2],
       [2, 2]])

In [22]:
np.dot(a,b)

array([[4, 4],
       [4, 4]])

### Bölme

In [23]:
dizi_1  /  dizi_2

array([0.66666667, 0.8       , 0.85714286, 0.88888889])