# Karşılaştırma ve Mantıksal Operatörleri

## 1) Karşılaştırma Operatörleri

Doğru veya Yanlışı test etmek için kullanıyoruz. 

İki diziyi karşılaştırırsak, geri dönüş değeri olarak basit bir Doğru(**True**) veya Yanlış(**False**) almayız. Karşılaştırmalar **elementen** yapılır. Bu, bir Boolean dizisi olarak geri dönüş almamızı sağlar.



In [2]:
import numpy as np

In [3]:
x = np.arange(1,6)

In [4]:
x

array([1, 2, 3, 4, 5])

In [5]:
x>2

array([False, False,  True,  True,  True])

In [6]:
x<2

array([ True, False, False, False, False])

In [7]:
x <= 2

array([ True,  True, False, False, False])

In [8]:
x >= 2

array([False,  True,  True,  True,  True])

In [9]:
x != 2

array([ True, False,  True,  True,  True])

In [10]:
x == 2

array([False,  True, False, False, False])

### 2 Dizi ile çalışmak

Diziler aynı boyutlarda olmalı.

In [11]:
y=np.arange(0,10,2)

In [12]:
y

array([0, 2, 4, 6, 8])

In [13]:
x # x dizisinde hatırlayalım

array([1, 2, 3, 4, 5])

In [14]:
y>x

array([False, False,  True,  True,  True])

In [15]:
y<x

array([ True, False, False, False, False])

In [16]:
y>=x

array([False,  True,  True,  True,  True])

In [17]:
y<=x

array([ True,  True, False, False, False])

In [18]:
y!=x

array([ True, False,  True,  True,  True])

In [19]:
y==x

array([False,  True, False, False, False])

## 2) Mantıksal Operatörler

## 2.1)numpy.logical_and

2 parametre alıyor.

--------------------------------------
| parametre 1 | parametre 2 | Çıktı   |
|-------------|-------------|---------|
| True        | True        | True    |
|-------------|-------------|---------|
| True        | False       | False   |
|-------------|-------------|---------|
| False       | True        | False   |
|-------------|-------------|---------|
| False       | False       | False   |
---------------------------------------

In [20]:
np.logical_and(True, False)

False

In [21]:
np.logical_and(True, True)

True

In [28]:
dizi=np.arange(2,12,3) # dizi oluşturalım

In [23]:
dizi

array([ 2,  5,  8, 11])

In [27]:
np.logical_and(dizi>0,dizi<12) # her bir dizi elemanı için sorguluyor

array([ True,  True,  True,  True])

In [29]:
np.logical_and(dizi>4,dizi<10) # her bir dizi elemanı için sorguluyor

array([False,  True,  True, False])

## 2.2)numpy.logical_or

2 parametre alıyor.

--------------------------------------
| parametre 1 | parametre 2 | Çıktı   |
|-------------|-------------|---------|
| True        | True        | True    |
|-------------|-------------|---------|
| True        | False       | True    |
|-------------|-------------|---------|
| False       | True        | True    |
|-------------|-------------|---------|
| False       | False       | False   |
---------------------------------------

In [31]:
np.logical_or(True, False)

True

In [32]:
np.logical_or(True, True)

True

In [41]:
dizi # dizimize tekrardan bir göz atalım

array([ 2,  5,  8, 11])

In [36]:
np.logical_or(dizi>0,dizi<12) 

array([ True,  True,  True,  True])

In [38]:
np.logical_or(dizi>4,dizi<10)# and operatöründen farklı sonuçlar verdiğini gördük 

array([ True,  True,  True,  True])

## 2.3)numpy.logical_not


1 parametre alıyor.

-----------------------------
| parametre   | Çıktı       |
|-------------|-------------|
| True        | False       |
|-------------|-------------|
| False       | True        | 
-----------------------------


In [39]:
np.logical_not(True)

False

In [40]:
np.logical_not(False)

True

In [42]:
dizi # dizimize tekrardan bir göz atalım

array([ 2,  5,  8, 11])

In [46]:
np.logical_not(dizi>0)# dizinin bütün elementleri sıfırdan büyük ama "not" operatörü onu tam tersini algılıyor

array([False, False, False, False])

In [45]:
np.logical_not(dizi<0)

array([ True,  True,  True,  True])