# Numpy Arraylerinin Indekslenmesi

In [1]:
import numpy as np

In [2]:
x = np.arange(2,20,2)

In [3]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
x[0]

2

In [5]:
x[1]

4

In [6]:
x[2]

6

#### Tersten Indekslenmesi (Çok kullanılmaz)

In [7]:
x[-1]

18

In [8]:
x[-2]

16

In [9]:
x[-3]

14

### dizi[ i (basla-dahil) : j (dur-hariç): k (adım) ] yapısı

In [10]:
x.size # eleman sayısı

9

In [11]:
x[0:9:1] # son elamanıda dahil etmek istersek j=size yapın

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
x[0:8:1]  # eğer " j= en son index no" yazarsak , son indexteki dahil olmaz

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
x[:9:1] # == x[0:9:1] , kendiliğinden i=0 ile başlar

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
x[:9:1] # == x[0:9:1] , kendiliğinden j=1 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
x[:] # == x , bütün elemanları gösterir

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
x[1:9:2]

array([ 4,  8, 12, 16])

In [18]:
x[1:9:3]

array([ 4, 10, 16])

In [19]:
x[2:9:4]

array([ 6, 14])

In [20]:
x[1:] # 1. indexten başla

array([ 4,  6,  8, 10, 12, 14, 16, 18])

### Belirli indexleri istenilen değer ile doldurmak

In [21]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
x[0:9:2]=0

In [23]:
x

array([ 0,  4,  0,  8,  0, 12,  0, 16,  0])

In [24]:
x[1:9:2]=1

In [25]:
x

array([0, 1, 0, 1, 0, 1, 0, 1, 0])

In [26]:
x[:3]=4 # 0. , 1. ve 2. indexlerin değerini 4 yapıyor.

In [27]:
x

array([4, 4, 4, 1, 0, 1, 0, 1, 0])

# İleri düzey İndeksleme

Çalışma mantığı :

    dizi_adı [ satır_indeksleri, sutün_indeksleri]

In [17]:
dizi=[[1,2],
      [4,6]]

In [18]:
y=np.array(dizi)

In [19]:
y

array([[1, 2],
       [4, 6]])

In [20]:
y[0,0]

1

In [32]:
y[0,1]

2

In [33]:
y[1,0]

4

In [34]:
y[1,1]

6

toplu bir şekilde alırsak.

In [35]:
y[[0,0],[0,1]]

array([1, 2])

In [36]:
y[[1,1],[0,1]]

array([4, 6])