# NumPy Arrayleri Manipülasyonu

## Düzleştirme

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = a.ravel()

In [5]:
a

array([1, 2, 3, 4, 5, 6])

### Yeniden Şekillendirme

In [6]:
s = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
s.shape

(2, 3)

In [8]:
s = s.reshape((3, 2)) # eleman boyutu önemli ona göre satırXsutünu ayarlayın

In [9]:
s

array([[1, 2],
       [3, 4],
       [5, 6]])

### Bölme(ayırma)

In [10]:
x = np.arange(9)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
x= np.array_split(x, 2)

In [13]:
x

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]

In [14]:
x = np.arange(9) # tekrardan çağıralım

In [15]:
x= np.array_split(x, 3)

In [16]:
x

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [17]:
x = np.arange(9) # tekrardan çağıralım

In [18]:
x= np.array_split(x, 4)

In [19]:
x

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### Birleştirme

In [20]:
k = np.array([1, 2, 3])

In [21]:
l = np.array([2, 3, 4])

In [22]:
m = np.stack((k, l))#satır halinde

In [23]:
m

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
np.stack((k , l ), axis=1)# sutün haline getirip birleştirdi

array([[1, 2],
       [2, 3],
       [3, 4]])